[nginx-bad-request-custom]
enabled = true
port = http,https
filter = nginx-bad-request-custom
logpath = @NGINX_LOG_PATH@
maxretry = 5
backend = polling
banaction = iptables-multiport
chain = DOCKER-USER
